61 enhance the datamodel with a connection between geschäftsjahr and auftrag
doerffler/DoePaAdmin pull request #63
Opened 2022-09-21 10:45 UTC by Jusdon

2022-09-21 10:51 UTC, timo2o1o requested changes
Hi @Jusdon,
would you please also develop the second part of the issue? We need a combobox on the management window for orders to be able to make use of this data model changes. Thanks :)!

2022-09-21 11:11 UTC, Jusdon commented
> Hi @Jusdon, would you please also develop the second part of the issue? We need a combobox on the management window for orders to be able to make use of this data model changes. Thanks :)!

I add the required commit

2022-09-21 11:23 UTC, timo2o1o requested changes
Please change the binding of the list with all business years to the GeschaeftsjahreViewModel

2022-09-21 11:23 UTC, timo2o1o commented on DoePaAdminViewModel/ManageAuftraegeViewModel.cs
> +        public ObservableCollection<Geschaeftsjahr> Geschaeftsjahre
Please do not bind to this property. Rollback this change and bind the combobox directly to the GeschaeftsjahreViewmodel as we do it in ManageMitarbeiterWindow with the cost centers

2022-09-21 11:23 UTC, timo2o1o commented on DoePaAdminApp/Views/ManageAuftraegeWindow.xaml
> +            <ComboBox ItemsSource="{Binding Geschaeftsjahre}" SelectedItem="{Binding SelectedAuftrag.Geschaeftsjahr, Mode=TwoWay}" DisplayMemberPath="Name" />
Please bind the ItemsSource directly to the GeschaeftsjahreViewmodel.

2022-09-22 07:07 UTC, timo2o1o commented on DoePaAdminApp/Views/MainWindow.xaml
> -                                          ImageSource="/Resources/sd_card_32x32.png"
Totally forgot about that one :D

2022-09-22 07:27 UTC, timo2o1o commented on DoePaAdminApp/Views/ManageAuftraegeWindow.xaml
> +                <DataGridComboBoxColumn Header="Geschäftsjahr" ItemsSource="{Binding Source={StaticResource Locator}, Path=ManageGeschaeftsjahreViewModel.Geschaeftsjahre, Mode=TwoWay}" SelectedItemBi
This is what I had in mind :D.

2022-09-22 07:27 UTC, timo2o1o approved these changes
Made some adjustments in another commit.

2022-09-22 07:36 UTC, merged

2022-09-22 08:26 UTC, Jusdon commented
> Made some adjustments in another commit.

Are you make these changes in another commit ? Or I ?

2022-09-22 08:53 UTC, timo2o1o commented
> > Made some adjustments in another commit.
> 
> Are you make these changes in another commit ? Or I ?

I did, in this commit:
https://github.com/doerffler/DoePaAdmin/pull/63/commits/c2a4d9908cf986cbe6e4581172de41c60f02e461